version: '3'
services:
  mysql:
    image: 'mysql:latest'
    container_name: 'mysql'
    restart: 'unless-stopped'
    expose:
      - '3306'
    environment:
      - 'MYSQL_RANDOM_ROOT_PASSWORD=true'
      - 'MYSQL_DATABASE=${MYSQL_DBMS}'
      - 'MYSQL_USER=${MYSQL_USER}'
      - 'MYSQL_PASSWORD=${MYSQL_PASSWORD}'
      - 'MYSQL_ALLOW_EMPTY_PASSWORD=true'
    volumes:
      - 'workclockit-database:/var/lib/mysql/'
    networks:
      - 'workclockit'
  php:
    build:
      context: .
    image: clockworkit-budget:latest
    container_name: 'php'
    networks:
      - 'workclockit'
    restart: 'unless-stopped'
volumes:
  workclockit-database:
networks:
  workclockit:
    driver: bridge
